version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/EDULOG
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Db@12345
    volumes:
      - ./src/main/resources:/app/config  # for firebase token, etc.

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: EDULOG
      MYSQL_ROOT_PASSWORD: Db@12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
